### ISSUE TITLE
Feedback & Issues

### ISSUE THREAD

**Issue by obtusedev** [lite-xl/lite-xl-lsp#16]
Currently trying to get this setup on lite-xl and have some questions.  

1. The text size on the popup widget is very tiny. Is there a way I can change font size?
2. Really nice font in the screenshots. Can you tell me what font this is? [link](https://raw.githubusercontent.com/jgmdev/lite-xl-lsp/master/screenshots/completion03.png), [link2](https://raw.githubusercontent.com/jgmdev/lite-xl-lsp/master/screenshots/completion04.png), [link3](https://raw.githubusercontent.com/jgmdev/lite-xl-lsp/master/screenshots/hover01.png)  
3. I am trying to setup rust-analyzer and the examples are missing details. There is also an issue where there is a 1s lag before the lsp autosuggestions popup which is very laggy.  
Inside `init.lua`  
```lua
local lspconfig = require "plugins.lsp.config"
lspconfig.rust_analyzer.setup()
```
This is doing nothing. I have rust-analyzer installed in `~/.local/bin` and it is in $PATH. I also have widget/ and lint+ installed.  
Instead I have to do the following in order to get it to work. This isn't mentioned anywhere and I had to use the existing `sumneko_lua` example in `config.lua` in order to hack it together.  
```lua
local lspconfig = require "plugins.lsp.config"
lspconfig.rust_analyzer.setup {
  settings = {
    Rust = {
      diagnostic = {
        enable = true
      }
    }
  }
}
```
In addition to that, there is a considerable lag between typing and autosuggestions popping up. It goes from lite-xl builtin autosuggest to lsp autosuggest and that thats ~ 1s which is very slow and noticable. I tried increasing the `requests_per_second` to more than 16, `requests_in_chunks` to `true`, and `incremental_changes` to `true` but that delay is still there. Perhaps this is a setting in lite-xl which I need to turn off but I assume the updated `autocomplete.lua` would have taken care of that.  

Anyways thanks for your time.

**Comment by jgmdev** [comment]
> Currently trying to get this setup on lite-xl and have some questions.
> 
> 1. The text size on the popup widget is very tiny. Is there a way I can change font size?
> 2. Really nice font in the screenshots. Can you tell me what font this is? [link](https://raw.githubusercontent.com/jgmdev/lite-xl-lsp/master/screenshots/completion03.png), [link2](https://raw.githubusercontent.com/jgmdev/lite-xl-lsp/master/screenshots/completion04.png), [link3](https://raw.githubusercontent.com/jgmdev/lite-xl-lsp/master/screenshots/hover01.png)

The screenshots are of initial work, later on I switched to monospaced font to be able to easily calculate resizing of the popups and made the font size smaller since sometimes an LSP could return lots of information (taking a lot of screen space). You can increase the overall interface fonts size by adding to your user init.lua something like:

```lua
if pcall(require, "plugins.scale") then
  local scale = require "plugins.scale"
  config.plugins.scale.mode = "ui"
  scale.set(1.45) -- <-- set this to your desired scaling value
end
```
or by setting the environment variable LITE_SCALE to your desired scale and then launching lite-xl eg:

```sh
LITE_SCALE=1.45 lite-xl
```

> 3. I am trying to setup rust-analyzer and the examples are missing details. There is also an issue where there is a 1s lag before the lsp autosuggestions popup which is very laggy.
>    Inside `init.lua`
> 
> ```lua
> local lspconfig = require "plugins.lsp.config"
> lspconfig.rust_analyzer.setup()
> ```
> 
> This is doing nothing. I have rust-analyzer installed in `~/.local/bin` and it is in $PATH. I also have widget/ and lint+ installed. Instead I have to do the following in order to get it to work. This isn't mentioned anywhere and I had to use the existing `sumneko_lua` example in `config.lua` in order to hack it together.
> 
> ```lua
> local lspconfig = require "plugins.lsp.config"
> lspconfig.rust_analyzer.setup {
>   settings = {
>     Rust = {
>       diagnostic = {
>         enable = true
>       }
>     }
>   }
> }
> ```
> 

That was a mistake on the readme, should have been:
```lua
lspconfig.rust_analyzer.setup {}
```
See the referenced commit above for details.

> In addition to that, there is a considerable lag between typing and autosuggestions popping up. It goes from lite-xl builtin autosuggest to lsp autosuggest and that thats ~ 1s which is very slow and noticable. I tried increasing the `requests_per_second` to more than 16, `requests_in_chunks` to `true`, and `incremental_changes` to `true` but that delay is still there. Perhaps this is a setting in lite-xl which I need to turn off but I assume the updated `autocomplete.lua` would have taken care of that.
> 

Rust analyzer sends the list of completion items along the whole markdown documentation, depending on the amount of results, parsing the json and stripping the markdown from it takes some time. Some other LSP servers work faster since they send the documentation when you select the autocomplete item from the completion box which is more efficient in our case. This is the reason you may see some lag between showing the autocomplete box and displaying rust-analyser results. Some weeks ago I added a work around so at least it doesn't stalls the UI when parsing the rust-analyzer results, but a workaround would be needed to prevent the default autocomplete box from been shown until the lsp suggestions are ready.

**Comment by obtusedev** [comment]
Thanks for clarifying as it makes more sense now. If by some change you remember the font, do let me know. Thanks
